import { createRoot } from "react-dom/client";
import { useRef, useState } from "react";
import { AppearancePicker, useAppearanceTheme, configureAppearance } from "../src";
import "./demo.css";
configureAppearance({ storagePrefix: "sunny-ui-demo" });
function Demo() {
  const [theme, setTheme] = useAppearanceTheme();
  const [filter, setFilter] = useState("全部");
  const [notice, setNotice] = useState("这里展示控件的触感与信息层次。选择、输入和弹窗都可以实际操作。");
  const confirmation = useRef<HTMLDialogElement>(null);
  return <div className="demo-shell">
    <aside className="appearance-sidebar"><a className="demo-brand" href="#overview"><span>S</span>Sunny UI</a><p>为你的产品选一种气质</p><nav aria-label="示例导航"><a href="#overview">工作台</a><a href="#materials">层次与材质</a><a href="https://github.com/xudong7587/sunny-ui-design-system">代码与规范 ↗</a></nav><small>色彩 × 质感 × 明暗</small></aside>
    <main><header className="demo-toolbar"><span>DESIGN PLAYGROUND</span><div><span>外观设置</span><AppearancePicker theme={theme} onThemeChange={() => setTheme(theme === "light" ? "dark" : "light")} /></div></header>
    <section className="demo-heading" id="overview"><p>YOUR SPACE, YOUR STYLE</p><h1>让界面有自己的气质。</h1><p>打开右上角外观设置。选颜色，再选材质，看看大小卡片、按钮和侧栏怎样一起变化。</p></section>
    <section className="demo-stats" aria-label="模块组成">{[["08","界面质感"],["10","多色搭配"],["02","明暗模式"]].map(([value,label]) => <article key={label} className="appearance-surface"><strong>{value}</strong><span>{label}</span></article>)}</section>
    <section className="demo-content"><article id="materials" className="appearance-surface"><p className="demo-eyebrow">MATERIAL LAYERS</p><h2>细节也有同样的质感</h2><p>外层面板、内层卡片与控件共用一套材质，但保留各自的重量和清晰度。</p><div className="demo-nested">{["主色 · 操作与选中","辅色 · 环境与层次","点缀 · 细节与氛围"].map((label,index) => <div key={label} className="appearance-surface-inner"><i style={{background:["var(--accent)","var(--appearance-secondary)","var(--appearance-tertiary)"][index]}} /><span>{label}</span></div>)}</div><div className="demo-actions"><button className="demo-primary">主要操作</button><button className="appearance-control">次要操作</button></div></article>
    <article className="appearance-surface"><p className="demo-eyebrow">READING & FEEDBACK</p><h2>颜色表达气氛，文字讲清内容</h2><label className="demo-field">项目名称<input className="appearance-control" defaultValue="我的工作空间" /></label><label className="demo-field">展示密度<select className="appearance-control" defaultValue="舒适"><option>舒适</option><option>紧凑</option></select></label><label className="demo-field">示例错误<input className="appearance-control" aria-invalid="true" aria-describedby="demo-error" placeholder="请输入名称" /></label><p id="demo-error" className="demo-error">名称不能为空；错误保留文字与边线提示。</p><p className="demo-status"><span />外观选择会保存在这个浏览器</p><blockquote>外层轻轻凸起，内层向下凹陷。文字保持清晰，状态仍然一眼可辨。</blockquote><p className="demo-note">这是本地交互示例。</p></article></section>
    <section className="appearance-surface demo-workbench" aria-labelledby="workbench-heading"><p className="demo-eyebrow">EVERYDAY COMPONENTS</p><h2 id="workbench-heading">同一种材质，也能适应日常工作界面</h2><div className="demo-notice appearance-surface-inner" role="status">{notice}</div><nav className="demo-tabs" aria-label="示例记录筛选">{["全部","已就绪","待处理"].map(value => <button type="button" className="appearance-control" key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value}</button>)}</nav><div className="demo-actions"><button type="button" className="demo-primary" onClick={() => confirmation.current?.showModal()}>打开确认弹窗</button><button type="button" className="appearance-control" onClick={() => setNotice("示例已经刷新，当前筛选和输入内容保留。")}>刷新示例</button><button type="button" className="appearance-control" disabled>暂不可用</button></div><div className="demo-table-wrap appearance-surface-inner"><table><caption>项目记录 · {filter}</caption><thead><tr><th scope="col">名称</th><th scope="col">状态</th></tr></thead><tbody>{[["外观标准与组件复用说明","已就绪"],["一个较长的项目名称，用于检查窄屏中的自然换行和完整阅读","待处理"]].filter(([,state]) => filter === "全部" || filter === state).map(([name,state]) => <tr key={name}><td>{name}</td><td><span className={state === "已就绪" ? "demo-badge demo-badge-success" : "demo-badge demo-badge-warning"}>{state}</span></td></tr>)}</tbody></table></div></section>
    <dialog className="appearance-dialog" ref={confirmation} aria-labelledby="demo-dialog-title"><div className="appearance-content"><header><div><h2 id="demo-dialog-title">确认本地示例</h2><p>弹窗沿用面板材质，保留清晰的内容和操作。</p></div><button type="button" className="appearance-control demo-close" aria-label="关闭确认弹窗" onClick={() => confirmation.current?.close()}>×</button></header><div className="appearance-surface-inner demo-notice">此操作只更新页面提示。</div><div className="demo-actions"><button type="button" className="demo-primary" onClick={() => { setNotice("已完成本地示例确认。"); confirmation.current?.close(); }}>确认示例</button><button type="button" className="appearance-control" onClick={() => confirmation.current?.close()}>取消</button></div></div></dialog>
    <footer>Sunny UI Design System · React + CSS tokens · GPL-3.0</footer></main></div>;
}
createRoot(document.getElementById("root")!).render(<Demo />);
